name: KFpicker
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - libffi=3.4.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.11.13
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.3.1
      - asttokens==3.0.0
      - astunparse==1.6.3
      - certifi==2025.7.9
      - charset-normalizer==3.4.2
      - colorama==0.4.6
      - comm==0.2.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - debugpy==1.8.14
      - decorator==5.2.1
      - executing==2.2.0
      - flatbuffers==25.2.10
      - fonttools==4.58.5
      - gast==0.6.0
      - google-pasta==0.2.0
      - greenlet==3.2.3
      - grpcio==1.73.1
      - h5py==3.14.0
      - idna==3.10
      - ipykernel==6.29.5
      - ipython==9.4.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - keras==3.10.0
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - lxml==6.0.0
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - namex==0.1.0
      - nest-asyncio==1.6.0
      - numpy==1.26.4
      - obspy==1.4.2
      - opt-einsum==3.4.0
      - optree==0.16.0
      - packaging==25.0
      - pandas==2.2.2
      - parso==0.8.4
      - pillow==11.3.0
      - platformdirs==4.3.8
      - prompt-toolkit==3.0.51
      - protobuf==5.29.5
      - psutil==7.0.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyzmq==27.0.0
      - requests==2.32.4
      - rich==14.0.0
      - scipy==1.16.0
      - six==1.17.0
      - sqlalchemy==1.4.54
      - stack-data==0.6.3
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-hub==0.16.1
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.1.0
      - tf-keras==2.19.0
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.14.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - wrapt==1.17.2
